# Client request launch file
string tag
string[] cmd
---
# Server response Content
bool success    # Indicate if the call succeed or failed
string message  # Message that elaborate on success or failure